services:
  - type: web
    name: bairesoft-react
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: public, no-cache
    routes:
      - type: rewrite
        source: /* 
        destination: /index.html
